# Generated by Django 4.0.2 on 2022-04-27 18:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_asset_options_alter_dataset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='keywords',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=255, null=True), blank=True, max_length=100, null=True, size=None),
        ),
    ]
