# Generated by Django 4.0.2 on 2022-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_asset_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='other_investigators',
            field=models.ManyToManyField(blank=True, related_name='other_investigators', to='apis.Person'),
        ),
    ]
