# Generated by Django 4.0.2 on 2022-06-01 17:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_grant_other_investigators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='keywords',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=255, null=True), blank=True, max_length=2000, null=True, size=None),
        ),
    ]
