# Generated by Django 4.0.2 on 2022-06-21 19:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_grant_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='funder_divisions',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, max_length=2000, size=None),
        ),
    ]
