# Generated by Django 4.0.2 on 2022-08-09 12:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_asset_approved_dataset_approved_funder_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='desired_collaboration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='websites',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=1000, null=True), blank=True, max_length=100, null=True, size=None),
        ),
    ]
