# Generated by Django 4.0.2 on 2022-10-04 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('emails', models.TextField()),
                ('other_emails', models.TextField(blank=True, null=True)),
                ('orcid', models.CharField(max_length=1000)),
                ('award_id', models.CharField(max_length=255)),
                ('award_title', models.TextField()),
                ('funder_name', models.CharField(max_length=255)),
                ('grant_keywords', models.TextField(blank=True, null=True)),
                ('grant_additional_keywords', models.TextField(blank=True, null=True)),
                ('dois', models.TextField(blank=True, null=True)),
                ('websites', models.TextField(blank=True, null=True)),
                ('person_keywords', models.TextField(blank=True, null=True)),
                ('desired_collaboration', models.TextField(blank=True, null=True)),
                ('person_comments', models.TextField(blank=True, null=True)),
                ('person_additional_comments', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('submission_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'survey',
                'ordering': ['id'],
            },
        ),
    ]
