# Generated by Django 4.0.2 on 2022-10-13 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('emails', models.TextField()),
                ('other_emails', models.TextField(blank=True, null=True)),
                ('orcid', models.CharField(max_length=1000)),
                ('award_id', models.CharField(max_length=255)),
                ('award_title', models.TextField()),
                ('funder_name', models.CharField(max_length=255)),
                ('grant_keywords', models.TextField(blank=True, null=True)),
                ('grant_additional_keywords', models.TextField(blank=True, null=True)),
                ('dois', models.TextField(blank=True, null=True)),
                ('websites', models.TextField(blank=True, null=True)),
                ('person_keywords', models.TextField(blank=True, null=True)),
                ('desired_collaboration', models.TextField(blank=True, null=True)),
                ('person_comments', models.TextField(blank=True, null=True)),
                ('person_additional_comments', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('submission_date', models.DateField(default=datetime.date.today)),
                ('is_copi', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'survey',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSurvey',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('emails', models.TextField()),
                ('other_emails', models.TextField(blank=True, null=True)),
                ('orcid', models.CharField(max_length=1000)),
                ('award_id', models.CharField(max_length=255)),
                ('award_title', models.TextField()),
                ('funder_name', models.CharField(max_length=255)),
                ('grant_keywords', models.TextField(blank=True, null=True)),
                ('grant_additional_keywords', models.TextField(blank=True, null=True)),
                ('dois', models.TextField(blank=True, null=True)),
                ('websites', models.TextField(blank=True, null=True)),
                ('person_keywords', models.TextField(blank=True, null=True)),
                ('desired_collaboration', models.TextField(blank=True, null=True)),
                ('person_comments', models.TextField(blank=True, null=True)),
                ('person_additional_comments', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('submission_date', models.DateField(default=datetime.date.today)),
                ('is_copi', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical survey',
                'verbose_name_plural': 'historical surveys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
