# Generated by Django 4.0.2 on 2022-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurvey',
            name='person_additional_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Communication preferences'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='person_additional_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Communication preferences'),
        ),
    ]
