# Generated by Django 4.0.2 on 2023-04-26 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_survey', '0003_alter_historicalsurvey_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurvey',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 13, 46, 29, 44205)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 13, 46, 29, 44205)),
        ),
    ]
