# Generated by Django 4.0.2 on 2023-04-26 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pi_survey', '0004_alter_historicalsurvey_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurvey',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
