# Generated by Django 4.0.2 on 2023-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_survey', '0005_alter_historicalsurvey_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurvey',
            name='award_id',
            field=models.CharField(max_length=255, verbose_name='Award ID'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='award_title',
            field=models.TextField(verbose_name='Award Title'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='dois',
            field=models.TextField(blank=True, null=True, verbose_name='DOIs'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='first_name',
            field=models.CharField(max_length=1000, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='funder_name',
            field=models.CharField(max_length=255, verbose_name='Funder Name'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='is_copi',
            field=models.BooleanField(default=False, verbose_name='Co-Pi tick box'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='last_name',
            field=models.CharField(max_length=1000, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='person_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='award_id',
            field=models.CharField(max_length=255, verbose_name='Award ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='award_title',
            field=models.TextField(verbose_name='Award Title'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dois',
            field=models.TextField(blank=True, null=True, verbose_name='DOIs'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(max_length=1000, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='funder_name',
            field=models.CharField(max_length=255, verbose_name='Funder Name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_copi',
            field=models.BooleanField(default=False, verbose_name='Co-Pi tick box'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name',
            field=models.CharField(max_length=1000, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='person_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
    ]
